# Generated by Django 3.0.7 on 2020-08-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
