# Generated by Django 3.0.7 on 2020-08-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0002_auto_20200801_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='fecha_modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
