# Generated by Django 3.0.7 on 2020-08-04 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0004_auto_20200801_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramite',
            old_name='numero',
            new_name='paso',
        ),
    ]
