# Generated by Django 3.0.7 on 2020-08-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0007_auto_20200804_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
