# Generated by Django 3.0.7 on 2020-08-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0008_cut_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
